name: Update syllabus
on: [workflow_dispatch]
jobs:
  selenium:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparing Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          architecture: 'x64'
      - name: Scraping
        working-directory: assets
        run: |
          pip3 install -U get-chrome-driver
          pip3 install -r requirements.txt
          python3 ../scripts/syllabusScraping.py
          python3 ../scripts/csvToJSON.py
      - name: Replace the result file
        working-directory: assets
        run: |
          bash ../scripts/replaceCurrentFile.sh
